### ISSUE TITLE
Edit text... then what?

### ISSUE THREAD

**Issue by ksignorini** [reyzor1991/pf2e-message-editor#1]
If I edit the text of a message, what do I hit to get it to actually change in the chat card? Closing the window with X doesn't save the change. There is no "save" type button.

**Comment by reyzor1991** [comment]
Save bnt

<img width="552" alt="Screenshot 2024-04-02 at 18 09 40" src="https://github.com/reyzor1991/pf2e-message-editor/assets/6688366/596d359f-f68d-49c0-ad6c-0abde82999f3">
